import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React from "react";

export default function Home() {
  return (

        <div className="mx-auto w-full h-full">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className=" bg-red-500  object-cover bg-top relative" style={{backgroundImage:'url("/img/hero.jpeg")'}}>
               <div className="w-full h-full hero-section" >

                   Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aliquam cum debitis deleniti dolorem error exercitationem facilis incidunt laborum, obcaecati officiis perferendis perspiciatis provident quisquam reiciendis rem saepe, voluptate!
               </div>
            </div>



        </div>

  )
}

