import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React from "react";
export default function Home() {
  return (

        <div className="mx-auto">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="mt-16 pt-2 bg-red-500 hero-section px-4">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aspernatur atque beatae blanditiis commodi corporis dolores doloribus ducimus, ea esse iusto magnam nobis porro quia quo recusandae sapiente sit voluptates.
            </div>




        </div>

  )
}

